/*
	HERE ARE PLACED TESTS METHODS TO EXTENSION DEVELOPMENT OR FIXING / CHECKING ISSUES:
*/

//CHANGES BACKGROUND COLOR A HTML VISUAL ELEMENT:
function test_1(a) {
    a.setAttribute("style", "background-color: cyan;");
}
